{% set name = "mdal" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lutraconsulting/MDAL/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: 11acb982122b3984eeac5c1963e9f53326eacb7f65accb9bbe745b751f654aba

build:

  number: 3

  run_exports:
    - {{ pin_subpackage('mdal', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
  host:
    - libgdal
    - hdf5
    - libnetcdf
    - libxml2
  run:

test:
  commands:
    - test -f $PREFIX/lib/libmdal$SHLIB_EXT  # [unix]
    - if not exist %LIBRARY_BIN%\\mdal.dll exit 1  # [win]
    - mdalinfo -h

about:
  home: https://www.mdal.xyz/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mesh Data Abstraction Layer
  description: |
    Mesh Data Abstraction Library (MDAL) is a C++ library for handling
    unstructured mesh data released with MIT license. It provides a single
    data model for multiple supported data formats. MDAL is used by QGIS
    for data access for mesh layers.
  doc_url: https://www.mdal.xyz/
  dev_url: https://www.mdal.xyz/contributing/index.html

extra:
  recipe-maintainers:
    - Runette
    - PeterPetrik
    - hobu
